language: node_js
node_js:
  - "8.9.4"
cache:
  directories:
    - "node_modules"
script: echo "Running tests against $(node -v)..."
env:
  - NG_CLI_ANALYTICS=true
jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage